name: Issue Tracker

on:
  issues:
    types: [opened]

permissions: write-all

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: |
          gh api -X PATCH \
          https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER} \
          -f body='This issue is closed.' \
          -f state='closed'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
