name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash
